FROM arm32v7/node:16-slim

WORKDIR /app/

COPY ./package*.json ./
COPY ./lib ./lib
COPY ./config ./config

RUN npm install --production

COPY ./app.js ./

EXPOSE 9229

USER node

CMD ["node", "--inspect=0.0.0.0:9229", "app.js"]
